"""add inforations table update

Revision ID: 2d18e3acf459
Revises: 8374fc24193a
Create Date: 2024-01-14 00:56:28.588739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d18e3acf459'
down_revision: Union[str, None] = '8374fc24193a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('money', sa.Integer(), nullable=True))
    op.drop_column('information', 'figi')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('figi', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('information', 'money')
    # ### end Alembic commands ###
