"""add inforations table update Colum

Revision ID: de8bc0ea309a
Revises: 2d18e3acf459
Create Date: 2024-01-14 01:04:38.686915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de8bc0ea309a'
down_revision: Union[str, None] = '2d18e3acf459'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
